calculator = input("what operation do you want to perform? (division multiplication addition or subtraction)")

if calculator : ("division")
print("Welcome to your division calculator!")
x = input("Enter first number : ")
y = input("Enter second number : ")
z = int(x) / int(y)
print(z)
if calculator : ("multiplication")
print("Welcome to your multiplication calculator!")
x = input("Enter first number : ")
y = input("Enter second number : ")
z = int(x) * int(y)
print(z)
if calculator : ("addition")
print("Welcome to your addition calculator!")
x = input("Enter first number : ")
y = input("Enter second number : ")
z = int(x) + int(y)
print(z)
if calculator : ("subtraction")
print("Welcome to your subtraction calculator!")
x = input("Enter first number : ")
y = input("Enter second number : ")
z = int(x) - int(y)
print(z)
